title: ChocoHeim
author: imdsoho
email: imdsoho@gmail.com
description: >
  | Drug Discovery and Development | Systems Biology | AI |

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- github.md

footer_icons:
- username: imdsoho/
  url: https://github.com/imdsoho
  icon: icon-github.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
